version: '3.3'

services:
    proxy:
        image: swarm/nav-lb
        ports:
            - target: 80
              published: 80
              protocol: tcp
              mode: host
            - target: 8080
              published: 8080
              protocol: tcp
              mode: host
            - target: 7045
              published: 7045
              protocol: tcp
              mode: host
            - target: 7046
              published: 7046
              protocol: tcp
              mode: host
            - target: 7047
              published: 7047
              protocol: tcp
              mode: host
            - target: 7048
              published: 7048
              protocol: tcp
              mode: host
        environment:
            UP_HOSTNAME: nav
        depends_on:
            - nav
        deploy:
            endpoint_mode: dnsrr
            restart_policy:
                delay: 10s
                window: 60s
            placement:
                constraints:
                    - node.role == manager
                
    nav:
        image: swarm/nav
        hostname: nav
        environment:
            PublicDnsName: swarm-master.westeurope.cloudapp.azure.com
            Accept_eula: "Y"
            auth: NavUserPassword
            username: myuser
            securepassword: 76492d1116743f0423413b16050a5345MgB8AHUAUABiADIARgB0AEEAeAB6ADcAMQAwAHYAVAAxAHEAMAB5AC8AbAB5AHcAPQA9AHwAOQBkADcAMQA0AGEANQA2ADMAYQA3ADIAMQAwADYAZABlADYAZQA2AGMAMwA3AGUAMABlADUAZgA5AGIAOQBhAGEANwA4ADIAYQBhAGIANgA4ADkAOQAwAGQANAAyADUAYgA5ADgANwBjADkAZgA5ADUAZgBhADYAZAA2AGMAZAA=
            UseSSL: "N"
            ClickOnce: "Y"
            databaseUserName: sa
            databaseSecurepassword: 76492d1116743f0423413b16050a5345MgB8AHUAUABiADIARgB0AEEAeAB6ADcAMQAwAHYAVAAxAHEAMAB5AC8AbAB5AHcAPQA9AHwAOQBkADcAMQA0AGEANQA2ADMAYQA3ADIAMQAwADYAZABlADYAZQA2AGMAMwA3AGUAMABlADUAZgA5AGIAOQBhAGEANwA4ADIAYQBhAGIANgA4ADkAOQAwAGQANAAyADUAYgA5ADgANwBjADkAZgA5ADUAZgBhADYAZAA2AGMAZAA=
            databaseServer: navdb
            databaseInstance: ""
            databaseName: cronus
            passwordKeyFile: C:\\ProgramData\\Docker\\secrets\\nav_password_key
        depends_on:
            - navdb
        secrets:
            - nav_password_key
        deploy:
            endpoint_mode: dnsrr
            replicas: 2
            restart_policy:
                delay: 30s
                max_attempts: 3
                window: 120s

    navdb:
        image: microsoft/mssql-server-windows-express
        environment:
            sa_password: Test123!
            ACCEPT_EULA: "Y"
            attach_dbs: "[{'dbName':'cronus','dbFiles':['C:\\\\dbs\\\\cronus_data.mdf','C:\\\\dbs\\\\cronus_log.ldf']}]"
        volumes:
            - C:/dbs/:C:/dbs
        deploy:
            endpoint_mode: dnsrr

secrets:
    nav_password_key:
        file: ./my.key